name: Test armv7l cpu option
on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  create_image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [raspi2_raspios]
        include:
        - target: raspi2_raspios
          cpu: cortex-a8
          cpu_info: cpuinfo/raspberrypi_zero2_w
          base_image: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2023-05-03/2023-05-03-raspios-bullseye-armhf-lite.img.xz
    steps:
#      - name: Checkout 
#        uses: actions/checkout@v2
      - name: Define the image name
        id: image_and_branch_name
        run: |
          if [ ${GITHUB_REF/refs\/tags\//} != ${GITHUB_REF} ]; then
            echo "INFO: ${GITHUB_REF/refs\/tags\//}" " not equal " "${GITHUB_REF}"
            echo "LOCAL_BRANCH=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
            echo "RELEASE_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME_SUFFIX=${GITHUB_REF/refs\/tags\//}-${{ matrix.target }}" >> $GITHUB_OUTPUT
          #  echo "CLONE_RELEASE=yes" >> $GITHUB_OUTPUT
          elif [ ${GITHUB_REF/refs\/heads\//} = "releng" ]; then
            echo "INFO: ${GITHUB_REF/refs\/heads\//} equals releng"
            echo "LOCAL_BRANCH=releng" >> $GITHUB_OUTPUT
            echo "RELEASE_NAME=releng" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME_SUFFIX=releng-${{ matrix.target }}" >> $GITHUB_OUTPUT
          #  echo "CLONE_RELEASE=yes" >> $GITHUB_OUTPUT
          elif [ ${GITHUB_REF/refs\/heads\//} != "${GITHUB_REF}" ]; then
            echo "INFO: ${GITHUB_REF/refs\/heads\//}" " not equals " "${GITHUB_REF}"
            echo "LOCAL_BRANCH=${GITHUB_REF/refs\/heads\//}" >> $GITHUB_OUTPUT
            echo "RELEASE_NAME=${GITHUB_REF/refs\/heads\//}" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME_SUFFIX=${GITHUB_REF/refs\/heads\//}-${{ matrix.target }}" >> $GITHUB_OUTPUT
          #  echo "CLONE_RELEASE=yes" >> $GITHUB_OUTPUT
          else
            echo "INFO: ${GITHUB_REF}" 
            echo "LOCAL_BRANCH=${GITHUB_REF}" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME_SUFFIX=${GITHUB_REF//\//-}-${{ matrix.target }}" >> $GITHUB_OUTPUT
          #  echo "CLONE_RELEASE=no" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Hello World File
        uses: pguyot/arm-runner-action@v2
        id: arm_runner_install
        with:
          image_additional_mb: 4096
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          optimize_image: yes
         # copy_repository_path: /opt/pynab
          commands: |
            touch /home/pi/helloworld

      - name: Compress the release image
        run: |
          mv ${{ steps.arm_runner_install.outputs.image }} rasperrypi-os-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img
          sudo xz -T 0 -v rasperrypi-os-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img
    
      - name: Upload the image artifact
        uses: actions/upload-artifact@v3
        with:
          name: rasperrypi-os-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img.xz
          path: rasperrypi-os-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img.xz
          if-no-files-found: error
          retention-days: 1

  create_release:
    name: Release
    runs-on: ubuntu-latest
    needs:
#      - test_suite
      - create_image
    if: github.ref == 'refs/heads/releng' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Define the release name
        id: release_name
        run: |
          if [ ${GITHUB_REF/refs\/tags\//} != ${GITHUB_REF} ]; then
             echo "RELEASE_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          elif [ ${GITHUB_REF/refs\/heads\//} = "releng" ]; then
             echo "RELEASE_NAME=releng" >> $GITHUB_OUTPUT
          else
             echo "RELEASE_NAME=${GITHUB_REF/refs\/heads\//}" >> $GITHUB_OUTPUT
          fi

      - name: Download the image artifacts
        uses: actions/download-artifact@v3

      - name: Create release with releng image
        if: github.ref == 'refs/heads/releng'
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          draft: true
          title: "Prerelease"
          files: pynab-${{ steps.release_name.outputs.RELEASE_NAME }}-*.img.xz/pynab-${{ steps.release_name.outputs.RELEASE_NAME }}-*.img.xz

      - name: Create release with release image
        if: startsWith(github.ref, 'refs/tags/')
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.release_name.outputs.RELEASE_NAME }}
          prerelease: false
          draft: true
          title: ${{ steps.release_name.outputs.RELEASE_NAME }}
          files: rasperrypi-os-${{ steps.release_name.outputs.RELEASE_NAME }}-*.img.xz/rasperrypi-os-${{ steps.release_name.outputs.RELEASE_NAME }}-*.img.xz

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: pguyot/arm-runner-action@v2
  #     with:
  #       cpu: cortex-a8
  #       image_additional_mb: 5120
  #       copy_artifact_path: bin/go-surveillance.tar.gz
  #       commands: |
  #           sudo df -h
  #           ## Update and install tools
  #           apt-get update && apt-get install -y wget tree git
            
  #           # install go
  #           #mkdir ~/src && cd ~/src
  #           wget https://dl.google.com/go/go1.19.4.linux-armv6l.tar.gz
  #           pwd
  #           sudo tar -C /usr/local -xzf go1.19.4.linux-armv6l.tar.gz
  #           rm go1.19.4.linux-armv6l.tar.gz
  #           export PATH=$PATH:/usr/local/go/bin
  #           export GOPATH=/gopath
  #           mkdir -p $GOPATH
  #           go version

  #           ## clone, checkout version and build gocv
  #           git clone https://github.com/hybridgroup/gocv.git
  #           cd gocv
  #           git checkout tags/v0.32.1
  #           make install
            
  #           # build go-surveillance 
  #           go get -u -d gocv.io/x/gocv
  #           echo $GOPATH
  #           ls /
  #           ls /gopath
  #           cd /gopath
  #           tree -d
  #           cd /go-surveillance
  #           make build
  #           cd bin
  #           tar -czvf go-surveillance.tar.gz go-surveillance
  #   - name: 'Upload Artifact'
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: go-surveillance-arm7.tar.gz
  #       path: go-surveillance.tar.gz
  #       retention-days: 5   

